get_player_status:
  name: Get player status
  description: Get current player status
  fields:
    player_id:
      name: Player
      description: Select player you want to execute call on
      required: true
      selector:
        entity:
          integration: synology_dsaudio
          domain: media_player


get_players:
  name: Get players
  description: Get list of available players
  fields:
    serial:
      name: Serial
      description: Serial of which you want to log available players
      example: 1NDVC86409
      selector:
        text:

remote_player_play_songs:
  name: Play songs on remote player
  description: PLay songs on remote player using their id's
  fields:
    player_id:
      name: Player
      description: Select player you want to execute call on
      required: true
      selector:
        entity:
          integration: synology_dsaudio
          domain: media_player
    songs:
      name: Song ids
      description: Ids of the songs you want to play (splitted by ,)
      example: music_2,music_5
      required: true
      selector:
        text:


remote_player_play_artist:
  name: Play artist on remote player
  description: Play artist on remote player using artist name
  fields:
    player_id:
      name: Player
      description: Select player you want to execute call on
      required: true
      selector:
        entity:
          integration: synology_dsaudio
          domain: media_player
    artist:
      name: Artist
      description: Artist
      example: Phil Collins
      required: true
      selector:
        text:

remote_player_play_album:
  name: Play album on remote player
  description: Play album on remote player using album name and album artist
  fields:
    player_id:
      name: Player
      description: Select player you want to execute call on
      required: true
      selector:
        entity:
          integration: synology_dsaudio
          domain: media_player
    album_name:
      name: Album name
      description: Name of the album
      example: Face Value
      required: true
      selector:
        text:
    album_artist:
      name: Artist
      description: Album artists
      example: Phil Collins
      required: true
      selector:
        text:

remote_player_control:
  name: Control remote player
  description: Control remote player playing status
  fields:
    player_id:
      name: Player
      description: Select player you want to execute call on
      required: true
      selector:
        entity:
          integration: synology_dsaudio
          domain: media_player
    action:
      name: Action
      description: Action for current playing media status
      example: play
      required: true
      selector:
          select:
            options:
              - play
              - pause
              - stop

remote_player_jump_to_song:
  name: Change currently playing song to position in playlist
  description: Change currently playing song to position in playlist
  fields:
    player_id:
      name: Player
      description: Select player you want to execute call on
      required: true
      selector:
        entity:
          integration: synology_dsaudio
          domain: media_player
    position:
      name: Position
      description: Position in playlist
      example: 25
      required: true
      selector:
        text:

remote_player_volume:
  name: Control remote player volume
  description: Control remote player volume
  fields:
    player_id:
      name: Player
      description: Select player you want to execute call on
      required: true
      selector:
        entity:
          integration: synology_dsaudio
          domain: media_player
    volume:
      name: Volume
      description: Volume of the player
      example: 25
      required: true
      selector:
        number:
          min: 0
          max: 100
          mode: slider

remote_player_shuffle:
  name: Set shuffle mode for remote player
  description: Set shuffle mode for remote player
  fields:
    player_id:
      name: Player
      description: Select player you want to execute call on
      required: true
      selector:
        entity:
          integration: synology_dsaudio
          domain: media_player
    shuffle:
      name: Shuffle
      description: Enable / Disable shufle
      required: true
      selector:
        boolean:


remote_player_clear_playlist:
  name: Clear playlist of player
  description: Clear playlist of player
  fields:
    player_id:
      name: Player
      description: Select player you want to execute call on
      required: true
      selector:
        entity:
          integration: synology_dsaudio
          domain: media_player

